"""
Multi-Objective Scoring Engine for Microfinance Capital Allocation.
Computes:
1. Financial Viability Score (F_i)
2. Urgent Need Index (N_i)
3. Social Impact Multiplier (S_i)
4. Composite Benefit Score (C_i)
"""

from typing import Dict, Tuple
import numpy as np
import pandas as pd


def compute_multiobjective_scores(
    df: pd.DataFrame,
    weights: Tuple[float, float, float] = (0.35, 0.35, 0.30)
) -> Tuple[pd.DataFrame, Dict[str, np.ndarray]]:
    """
    Computes normalized financial, need, social impact, and composite scores.

    Parameters:
    -----------
    df : pd.DataFrame
        Applicant DataFrame generated by data_generator.
    weights : tuple of 3 floats
        Weights for (Financial, Need, Social Impact). Must sum to 1.0.

    Returns:
    --------
    df_scored : pd.DataFrame
        Enriched DataFrame with individual and composite scores.
    arrays_dict : dict
        Dictionary of numpy arrays containing:
        - 'composite_scores': C in [0, 1]^N
        - 'financial_scores': F in [0, 1]^N
        - 'need_scores': N in [0, 1]^N
        - 'impact_scores': S in [0, 1]^N
        - 'loan_amounts': w in R^N
        - 'group_indicators': G in {0, 1}^N (0: Group A, 1: Group B)
    """
    omega_F, omega_N, omega_S = weights
    assert np.isclose(omega_F + omega_N + omega_S, 1.0), "Weights must sum to 1.0"

    income_median = df["monthly_income"].median()

    # 1. Financial Viability Score (F_i in [0, 1])
    # Higher repayment fidelity, lower DTI, moderate/stable income
    f_score = (
        0.40 * (1.0 - np.clip(df["dti_ratio"].values, 0.0, 1.0)) +
        0.40 * np.clip(df["repayment_history"].values, 0.0, 1.0) +
        0.20 * np.clip(df["monthly_income"].values / (income_median * 1.5), 0.0, 1.0)
    )
    f_score = np.clip(f_score, 0.0, 1.0)

    # 2. Urgent Need Index (N_i in [0, 1])
    # Higher poverty index, more dependents, lower absolute income
    n_score = (
        0.50 * np.clip(df["poverty_index"].values, 0.0, 1.0) +
        0.30 * np.clip(df["dependents"].values / 6.0, 0.0, 1.0) +
        0.20 * np.clip(1.0 - (df["monthly_income"].values / (income_median * 2.0)), 0.0, 1.0)
    )
    n_score = np.clip(n_score, 0.0, 1.0)

    # 3. Social Impact Multiplier (S_i in [0, 1])
    # Women-led enterprise boost, marginalized group equity boost, micro-loan leverage
    women_boost = np.where(df["is_women_led"].values, 1.0, 0.25)
    group_boost = np.where(df["demographic_group"].values == "Group_A_Marginalized", 1.0, 0.35)
    size_factor = np.clip(1.0 - (df["requested_amount"].values / 60000.0), 0.2, 1.0)

    s_score = (
        0.45 * women_boost +
        0.35 * group_boost +
        0.20 * size_factor
    )
    s_score = np.clip(s_score, 0.0, 1.0)

    # 4. Composite Utility Score (C_i)
    c_score = omega_F * f_score + omega_N * n_score + omega_S * s_score

    # Group binary indicator: 0 for Group A (Marginalized), 1 for Group B (General)
    group_binary = np.where(df["demographic_group"].values == "Group_A_Marginalized", 0, 1)

    df_scored = df.copy()
    df_scored["financial_score"] = np.round(f_score, 4)
    df_scored["need_index"] = np.round(n_score, 4)
    df_scored["social_impact_score"] = np.round(s_score, 4)
    df_scored["composite_score"] = np.round(c_score, 4)
    df_scored["group_binary"] = group_binary

    arrays_dict = {
        "composite_scores": c_score,
        "financial_scores": f_score,
        "need_scores": n_score,
        "impact_scores": s_score,
        "loan_amounts": df["requested_amount"].values,
        "group_indicators": group_binary
    }

    return df_scored, arrays_dict


if __name__ == "__main__":
    from src.data_generator import generate_microfinance_cohort
    df = generate_microfinance_cohort(n_applicants=6, seed=42)
    df_scored, arr = compute_multiobjective_scores(df)
    print(df_scored[["applicant_id", "composite_score", "financial_score", "need_index", "social_impact_score"]])
